env:
  - CXX=g++-4.8
language: php
cache:
  directories:
    - node_modules
php:
  - '7.2'
  - '7.1'
  - '7.0'
before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 6
  - nvm use 6
  - npm install -g yarn
  - yarn install
install:
  - composer install
  - php artisan key:generate
  - yarn run dev
script:
  - ./vendor/bin/phpunit
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
notifications:
  email:
    on_success: never
    on_failure: never